name: knyghtes
favicon: null
layout_spectrum: 0.07263851468451321
typography_spectrum: 0.6559498726855963
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7051647081971169
  lightness: 0.11463912739418447
  saturation: 0.865146673982963
  rhythmicContrast: 0.5566177463624626
purpose: []
